spring:
  #数据库驱动
  datasource:
    #这里的配置主要解决jdbc和MySQL版本不匹配的问题
    url: jdbc:mysql:///epidemic?useSSL=true&userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xpyaiyune158957
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    encoding: UTF-8
#    cache: false


mybatis:
  #开启别名
  type-aliases-package: com.nuhu.epidemic.pojo
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: true
  #标识是哪一种数据库
  helper-dialect: postgresql
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
  #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
  page-size-zero: true

server:
  port: 8080
